name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'


      - run: npm install
      - run: npm run build
      # - run: mkdir -p build
      # - run: npm i markdown-to-html-cli -g
      # - run: markdown-to-html --output build/index.html --favicon 'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>üèûÔ∏è</text></svg>' --github-corners https://github.com/jaywcjlove/generated-badges

      - name: Create idoc config
        run: |
          cat > idoc.yml << EOF
          site: "Generated Badges {{version}}"
          menus:
            Home: index.html
            Sponsor: https://jaywcjlove.github.io/#/sponsor
          footer: |
            <a href="https://jaywcjlove.github.io/#/sponsor" target="_blank">Sponsor</a> ‚Ä¢ 
            <a href="https://jaywcjlove.github.io/changelog-generator" target="_blank">Changelog Generator</a> ‚Ä¢ 
            <a href="https://jaywcjlove.github.io/github-action-contributors" target="_blank">Contributors</a> ‚Ä¢ 
            <a href="https://jaywcjlove.github.io/github-action-read-file" target="_blank">Read File Content</a> ‚Ä¢ 
            <a href="https://jaywcjlove.github.io/create-tag-action" target="_blank">Create Tag</a>
            <br />
            Released under the MIT License. Copyright ¬© {{idocYear}} Kenny Wong<br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}
          
          EOF
  
      - run: npm install idoc@1 -g
      - run: idoc
  

      - name: Generate blue badges
        # uses: jaywcjlove/generated-badges@main
        uses: ./
        with:
          label: color
          status: blue
          output: dist/blue.svg

      - name: Generate cyan badges
        uses: ./
        with:
          label: color
          status: cyan
          color: cyan
          output: dist/cyan.svg

      - name: Generate green badges
        uses: ./
        with:
          label: color
          status: green
          color: green
          output: dist/green.svg

      - name: Generate yellow badges
        uses: ./
        with:
          label: color
          status: yellow
          color: yellow
          output: dist/yellow.svg

      - name: Generate red badges
        uses: ./
        with:
          label: color
          status: red
          color: red
          output: dist/red.svg

      - name: Generate pink badges
        uses: ./
        with:
          label: color
          status: pink
          color: pink
          output: dist/pink.svg

      - name: Generate purple badges
        uses: ./
        with:
          label: color
          status: purple
          color: purple
          output: dist/purple.svg

      - name: Generate grey badges
        uses: ./
        with:
          label: color
          status: grey
          color: grey
          output: dist/grey.svg

      - name: Generate black badges
        uses: ./
        with:
          label: color
          status: black
          color: black
          output: dist/black.svg

      - name: Generate gradient badges
        uses: jaywcjlove/generated-badges@main
        with:
          label: gradient
          status: pink,F78642
          gradient: pink,F78642
          output: dist/gradient.svg

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: dist/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (Â∞èÂºüË∞ÉË∞É‚Ñ¢|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/react-codemirror/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  
            
            ${{ steps.changelog.outputs.changelog }}

            ```yml
            - run: mkdir -p build

            - name: Generate Badges
              uses: jaywcjlove/generated-badges@main
              with:
                label: color
                status: cyan
                output: build/cyan.svg

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: xxxxxxx
                publish_dir: ./build
            ```

            ![blue badges](https://jaywcjlove.github.io/generated-badges/blue.svg) ![cyan badges](https://jaywcjlove.github.io/generated-badges/cyan.svg) ![green badges](https://jaywcjlove.github.io/generated-badges/green.svg) ![yellow badges](https://jaywcjlove.github.io/generated-badges/yellow.svg) ![red badges](https://jaywcjlove.github.io/generated-badges/red.svg) ![pink badges](https://jaywcjlove.github.io/generated-badges/pink.svg) ![purple badges](https://jaywcjlove.github.io/generated-badges/purple.svg) ![grey badges](https://jaywcjlove.github.io/generated-badges/grey.svg) ![black badges](https://jaywcjlove.github.io/generated-badges/black.svg) ![gradient badges](https://jaywcjlove.github.io/generated-badges/gradient.svg)

      # - run: npm install @jsdevtools/npm-publish -g
      # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./package.json

      # - name: üì¶ generated-badges publish to NPM
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     package: ./package.json

      - run: npm publish --access public --provenance
        name: üì¶ generated-badges publish to NPM
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}